/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteRouteImport } from './routes/session.$sessionId/route'
import { Route as SessionSessionIdIndexRouteImport } from './routes/session.$sessionId/index'
import { Route as SessionSessionIdFilesRouteImport } from './routes/session.$sessionId/files'
import { Route as SessionSessionIdDashboardRouteImport } from './routes/session.$sessionId/dashboard'
import { Route as SessionSessionIdChatRouteImport } from './routes/session.$sessionId/chat'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRouteRoute = SessionSessionIdRouteRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdIndexRoute = SessionSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionSessionIdRouteRoute,
} as any)
const SessionSessionIdFilesRoute = SessionSessionIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SessionSessionIdRouteRoute,
} as any)
const SessionSessionIdDashboardRoute =
  SessionSessionIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SessionSessionIdRouteRoute,
  } as any)
const SessionSessionIdChatRoute = SessionSessionIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SessionSessionIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/session/$sessionId': typeof SessionSessionIdRouteRouteWithChildren
  '/session/$sessionId/chat': typeof SessionSessionIdChatRoute
  '/session/$sessionId/dashboard': typeof SessionSessionIdDashboardRoute
  '/session/$sessionId/files': typeof SessionSessionIdFilesRoute
  '/session/$sessionId/': typeof SessionSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/session/$sessionId/chat': typeof SessionSessionIdChatRoute
  '/session/$sessionId/dashboard': typeof SessionSessionIdDashboardRoute
  '/session/$sessionId/files': typeof SessionSessionIdFilesRoute
  '/session/$sessionId': typeof SessionSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/session/$sessionId': typeof SessionSessionIdRouteRouteWithChildren
  '/session/$sessionId/chat': typeof SessionSessionIdChatRoute
  '/session/$sessionId/dashboard': typeof SessionSessionIdDashboardRoute
  '/session/$sessionId/files': typeof SessionSessionIdFilesRoute
  '/session/$sessionId/': typeof SessionSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/session/$sessionId'
    | '/session/$sessionId/chat'
    | '/session/$sessionId/dashboard'
    | '/session/$sessionId/files'
    | '/session/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/session/$sessionId/chat'
    | '/session/$sessionId/dashboard'
    | '/session/$sessionId/files'
    | '/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/session/$sessionId'
    | '/session/$sessionId/chat'
    | '/session/$sessionId/dashboard'
    | '/session/$sessionId/files'
    | '/session/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SessionSessionIdRouteRoute: typeof SessionSessionIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/': {
      id: '/session/$sessionId/'
      path: '/'
      fullPath: '/session/$sessionId/'
      preLoaderRoute: typeof SessionSessionIdIndexRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
    '/session/$sessionId/files': {
      id: '/session/$sessionId/files'
      path: '/files'
      fullPath: '/session/$sessionId/files'
      preLoaderRoute: typeof SessionSessionIdFilesRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
    '/session/$sessionId/dashboard': {
      id: '/session/$sessionId/dashboard'
      path: '/dashboard'
      fullPath: '/session/$sessionId/dashboard'
      preLoaderRoute: typeof SessionSessionIdDashboardRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
    '/session/$sessionId/chat': {
      id: '/session/$sessionId/chat'
      path: '/chat'
      fullPath: '/session/$sessionId/chat'
      preLoaderRoute: typeof SessionSessionIdChatRouteImport
      parentRoute: typeof SessionSessionIdRouteRoute
    }
  }
}

interface SessionSessionIdRouteRouteChildren {
  SessionSessionIdChatRoute: typeof SessionSessionIdChatRoute
  SessionSessionIdDashboardRoute: typeof SessionSessionIdDashboardRoute
  SessionSessionIdFilesRoute: typeof SessionSessionIdFilesRoute
  SessionSessionIdIndexRoute: typeof SessionSessionIdIndexRoute
}

const SessionSessionIdRouteRouteChildren: SessionSessionIdRouteRouteChildren = {
  SessionSessionIdChatRoute: SessionSessionIdChatRoute,
  SessionSessionIdDashboardRoute: SessionSessionIdDashboardRoute,
  SessionSessionIdFilesRoute: SessionSessionIdFilesRoute,
  SessionSessionIdIndexRoute: SessionSessionIdIndexRoute,
}

const SessionSessionIdRouteRouteWithChildren =
  SessionSessionIdRouteRoute._addFileChildren(
    SessionSessionIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SessionSessionIdRouteRoute: SessionSessionIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
